# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fd_cususer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactnumber', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
