# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fd_cususer',
            name='contactnumber',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
