# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdmain', '0002_auto_20171123_0053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fd_cususer',
        ),
    ]
