# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fdmain', '0004_fd_cususer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_cususer',
            name='addressdetails',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='cuslocation',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='cusname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='mealtype',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='orderdate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='ordertype',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='tiffincount',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='tiffintype',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
