# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdmain', '0010_remove_fd_cususer_tiffintype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fd_cususer',
            name='cusname',
        ),
        migrations.RemoveField(
            model_name='fd_cususer',
            name='mealtype',
        ),
        migrations.RemoveField(
            model_name='fd_cususer',
            name='ordertype',
        ),
    ]
