# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdmain', '0011_auto_20171123_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_cususer',
            name='cusname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='mealtype',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
