# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdmain', '0013_auto_20171123_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fd_cususer',
            name='addressdetails',
        ),
        migrations.RemoveField(
            model_name='fd_cususer',
            name='cuslocation',
        ),
        migrations.RemoveField(
            model_name='fd_cususer',
            name='tiffincount',
        ),
    ]
