# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdmain', '0015_remove_fd_cususer_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_cususer',
            name='addressdetails',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='cuslocation',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='fd_cususer',
            name='tiffincount',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
