# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fdmain', '0016_auto_20171123_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_cususer',
            name='orderdate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
